// <auto-generated />
using System;
using IndexFragmentation.Test.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndexFragmentation.Test.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20250806064331_AddIndex")]
    partial class AddIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndexFragmentation.Test.Db.Model.FragmentationTestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid4")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Guid7")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Ulid")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("Guid4");

                    b.HasIndex("Guid7");

                    b.HasIndex("Ulid");

                    b.ToTable("FragmentationTest");
                });
#pragma warning restore 612, 618
        }
    }
}
