// <auto-generated />
using System;
using IndexFragmentation.Test.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IndexFragmentation.Test.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20250809130648_StatResult")]
    partial class StatResult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IndexFragmentation.Test.Db.Model.FragmentationTestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("Guid4")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Guid7")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Ulid")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<Guid>("UuidNext")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Guid4");

                    b.HasIndex("Guid7");

                    b.HasIndex("Ulid");

                    b.HasIndex("UuidNext");

                    b.ToTable("FragmentationTest", (string)null);
                });

            modelBuilder.Entity("IndexFragmentation.Test.Db.Model.FragmentationTestResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Guid4")
                        .HasColumnType("float");

                    b.Property<double>("Guid7")
                        .HasColumnType("float");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalCount")
                        .HasColumnType("bigint");

                    b.Property<double>("Ulid")
                        .HasColumnType("float");

                    b.Property<double>("UuidNext")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FragmentationTestResult", (string)null);
                });

            modelBuilder.Entity("IndexFragmentation.Test.Db.Model.IndexFragmentationInfo", b =>
                {
                    b.Property<double>("AvgFragmentationInPercent")
                        .HasColumnType("float");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("IndexFragmentationView", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
